management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,refresh"
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.uniflow: DEBUG
    org.springframework.cloud: INFO
