server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://enroll_postgres:5432/enroll_db
    username: enroll_user
    password: enroll_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: 8pFcrOSF8T9yq2ccOwkmecKcStATsrMftKCFVzdCqXeD5biqlt
    issuer: uniflow-identity-service
